### ISSUE TITLE
Abstract displayed on documentation

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer.github.io#21] opened 2020-08-29 10:04 UTC
An abstract is displayed below the title of each documentation.
Aside the fact it's not readable we don't want to have this. It's most probably an accidental left-over from updating the jekyll/sass thing (#11) where we were playing around with that.

_In the picture I choose blue to highlight the error because of the orange/red image in the background)_

![abstract](https://user-images.githubusercontent.com/4354359/91634282-95ecc880-e9ef-11ea-811f-4aa2eb841689.png)

**Comment by nipafx** [comment] 2020-08-29 10:53
Because I could not reproduce this problem locally, I figured it must be due to different Ruby/Jekyll/etc versions, so we updated Ruby to the version I'm using locally (2.6 - see dea4cef) and committed `Gemfile.lock` to pin gem versions (see f542eed).

**Closed as completed by nipafx** 2020-08-29 10:53 UTC
Labels: 🐞 type: bug, 📢 up for grabs, 📖 theme: layout
